<p class='notebook_header'><b>CS 309 - Robot Learning</b></p>
<p class='notebook_header'>Homework 1</p>
<hr class='separate' />

<p class='section_header'><b>Part 1: Linear Algebra</b></p>

Implement the following matrix/vector functions using NumPy operations.

If the function's operation isn't possible for matrix or vector inputs, return None.

In [2]:
import numpy as np


In [3]:
def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    try:
        return a.dot(b)
    except:
        return None

def divide(a, b):
    return None

def transpose(a):
    return a.transpose()

def two_norm(a):
    return np.linalg.norm(a)

<p>Using your code from above, solve the following equations. If an operation isn't possible, put None or comment with "Not Possible".</p>

$$
u = \begin{bmatrix} 2 \\ 3 \\ 9 \end{bmatrix}, \:
v = \begin{bmatrix} -2 \\ 1 \\ 8 \end{bmatrix}
$$  


In [4]:
u = np.array([
    [2],
    [3],
    [9]
])

v = np.array([
    [-2],
    [1],
    [8]
])

$$ u + v = \begin{bmatrix} 0 \\ 4 \\ 17 \end{bmatrix} $$  

$$ u - v = \begin{bmatrix} 4 \\ 2 \\ 1 \end{bmatrix} $$  

$$ u * v = \text{Not Possible} $$  

$$ u \div v = \text{Not Possible} $$  


In [5]:
# YOUR CODE HERE

u_plus_v = add(u, v)
print(u_plus_v)

u_minus_v = subtract(u, v)
print(u - v)

u_mult_v = multiply(u, v)
print(u_mult_v)

u_div_v = divide(u, v)
print(u_div_v)

[[ 0]
 [ 4]
 [17]]
[[4]
 [2]
 [1]]
None
None


$$ u^{\;T} * v = \; 71 $$  

$$ u * v^{\;T} = \begin{bmatrix} -4 & 2 & 17 \\ -6 & 3 & 24 \\ -18 & 9 & 72 \end{bmatrix} $$  

$$ u^{\;T} * u = \; 94 $$  

$$ \left \| u \right \|_{2}^{2} = 9.695359714832659 $$  


In [6]:
# YOUR CODE HERE

u_transpose_v = multiply(transpose(u), v)
print(u_transpose_v)

u_v_transpose = multiply(u, transpose(v))
print(u_v_transpose)

u_transpose_u = multiply(transpose(u), u)
print(u_transpose_u)

two_norm_u = two_norm(u)
print(two_norm_u)

[[71]]
[[ -4   2  16]
 [ -6   3  24]
 [-18   9  72]]
[[94]]
9.695359714832659


<hr class='light-separate' />

$$
A = \begin{bmatrix} 1 & 6 & 5\\ 0 & -4 & -1\\ 7 & 2 & 3 \end{bmatrix}, \: 
B = \begin{bmatrix} 3 & 1 & 1\\ 4 & -1 & 7\\ 7 & 0 & 0 \end{bmatrix}
$$  


$$ A + B = \begin{bmatrix} 4 & 7 & 6 \\ 4 & -5 & 6 \\ 14 & 2 & 3 \end{bmatrix} $$  

$$ A - B = \begin{bmatrix} -2 & 5 & 4 \\ -4 & -3 & -8 \\0 & 2 & 3 \end{bmatrix} $$  

$$ A * B = \begin{bmatrix} 62 & -5 & 43 \\ -23 & 4 & -28 \\ 50 & 5 & 21 \end{bmatrix} $$  

$$ A \div B = \text{Not Possible} $$ 


In [7]:
# YOUR CODE HERE
a = np.array([
    [1, 6, 5],
    [0, -4, -1],
    [7, 2, 3]
])
b = np.array([
    [3, 1, 1],
    [4, -1, 7],
    [7, 0, 0]
])
a_plus_b = add(a, b)
print(a_plus_b)

a_minus_b = subtract(a, b)
print(a_minus_b)

a_mult_b = multiply(a, b)
print(a_mult_b)

a_div_b = divide(a, b)
print(a_div_b)

[[ 4  7  6]
 [ 4 -5  6]
 [14  2  3]]
[[-2  5  4]
 [-4 -3 -8]
 [ 0  2  3]]
[[ 62  -5  43]
 [-23   4 -28]
 [ 50   5  21]]
None


<hr class='light-separate' />

$$
C = \begin{bmatrix} 5 & 1 \\ -1 & 7 \\ 3 & 0 \end{bmatrix}
$$  


In [8]:
c = np.array([[5, 1],
              [-1, 7],
              [3, 0]])

Right Pseudo Inverse of C:
$$
\begin{bmatrix} -0.25 & 0 & 0.5 \\ 0.03125 & 0.1484375 & 2.5625 \end{bmatrix}
$$  

Left Pseudo Inverse of C:
\begin{bmatrix} 0.1443299 & -0.02061856 & 0.08591065 \\ 0.0257732 & 0.13917526 & 0.00343643 \end{bmatrix}
  


In [9]:
# YOUR CODE HERE

right_pinv = c.transpose().dot(np.linalg.inv(c.dot(c.transpose())))
print(right_pinv)

left_pinv = (np.linalg.inv(c.transpose().dot(c)).dot(c.transpose()))
print(left_pinv)

[[-0.25       0.         0.5      ]
 [ 0.03125    0.1484375  0.0625   ]]
[[ 0.1443299  -0.02061856  0.08591065]
 [ 0.0257732   0.13917526  0.00343643]]


<hr class='separate' />

<p class='section_header'><b>Part 2: Regression</b></p>

**Write** the equation for Ordinary Least Squares below. 

$$\theta = (X^T X)^{-1} X^T y$$

$$ \sum_{i = 1}^n (y_i - \sum_{a = 1}^m b_ax_a + b_0)^2 $$



**Explain** Ordinary Least Squares in terms of what it optimizes.

**Ordinary Least Squares minimizes the sum of the squared residuals.**

In [10]:
# Don't change this cell!
# Load in the data about the study on students
train = np.loadtxt('train.csv', delimiter=',')
x_0, x_1, x_2, y = train.T
X_train = np.array([x_0, x_1, x_2]).T
Y_train = np.expand_dims(y, 1)

test = np.loadtxt('test.csv', delimiter=',')
x_0, x_1, x_2, y = test.T
X_test = np.array([x_0, x_1, x_2]).T
Y_test = np.expand_dims(y, 1)

There was an imaginary study done on 101 students at Crest University. The study surveyed students for the amount they have spent on electronics, books, pencils, and foods. 

Given that the **amount students spend on electronics ($Y$)** is linearly related to the **amount they spend on books ($ X_{0} $), pencils ($ X_{1}$)**, and **food ($ X_{2}$)**, 
**implement** the Ordinary Least Squares method to model this regression problem.

The data is read in from the previous cell code. **X_train** has the input features, while **Y_train** has corresponding target outputs.

After finding a solution, try to measure the error between your predictions and the ground truth. 

In [11]:
# TODO: Create code for OLS here. DO NOT use any other libraries in your first implementation.

def OLS(X, y):
    return np.linalg.solve(np.dot(X.T, X), np.dot(X.T, y))

# TODO: check against training data
theta = OLS(X_train,Y_train)

# TODO: test your model on testing data
predicted_y = np.dot(X_train, theta)
error = ((predicted_y - Y_train) ** 2).mean()
print(f"Error: {error}")

Error: 22.791845424466484


**Explain** what collinearity is.

**Collinearity is a condition where variables are highly correlated such that they express a linear relationship in a regression model.**

**Write** the equation for Ridge Regression below. 

$$ \theta = (X^TX + \lambda I)^{-1}X^TY $$

$$ min(\sum_{i = 1}^n (y_i - \sum_{a = 1}^m b_ax_a + b_0)^2 + \lambda \sum_{a = 1}^m b_a^2)$$


**Explain** what the purpose ridge regression and its advantages and disadvantages over OLS.

- RRS increases bias, but reduces model variance

**Ridge Regression is a technique to use when the data has collinearity. If OLS were used in these circumstances, the large variances between estimates would deviate the observed value away from the actual value. However, when you have more features than observations, Ridge Regression can create bias.**

**Implement** your regression model with ridge regression below.

In [12]:
# TODO: Create code for Ridge Regression here. DO NOT use any other libraries
# TODO: Plot your regression line over the input points.

def RR(X, y, ridge=0.001):
    return np.linalg.solve(np.dot(X.T, X) + ridge * np.identity(len(X.T)), np.dot(X.T, y))
#     return (np.linalg.inv((X.T).dot(X) + ridge * np.identity(len(X.T)))).dot((X.T).dot(y))
#     pass

# TODO: check against training data
theta = RR(X_train,Y_train)
print(theta)

predicted_y = np.dot(X_train, theta)
error = ((predicted_y - Y_train) ** 2).mean()
print(f"Error: {error}")

# Testing various values for the ridge parameter
theta = RR(X_train,Y_train, 500000)
print(theta)

predicted_y = np.dot(X_train, theta)
error = ((predicted_y - Y_train) ** 2).mean()
print(f"2Error: {error}")



# TODO: test your model on testing data


[[ 1.92516587]
 [-0.70151584]
 [ 0.54358107]]
Error: 22.785151592876804
[[ 0.35554326]
 [-0.04593887]
 [ 0.48139218]]
2Error: 3113.397458772699


**Explain** the differences ridge regression created for theta compared to OLS, and why these differences even existed. Also try different values for the ridge parameters and describe how they effect your results.

**Our theta values affected by ridge regression were slightly smaller compared to those affected by OLS. This is because we have a shrinkage penalty within ridge regression, for the purpose of decreasing the variance of the line, that doesn’t exist within OLS. Larger values for the ridge parameter increase the error.**

There are other regularizers other than ridge regression, such as LASSO. **Explain** the differences between LASSO and Ridge Regression and how it changes the solution mathematically.

The shrinkage penalty for LASSO is $$\lambda \sum_{a=1}^m |b_a|$$ whereas the shrinkage penalty for Ridge Regression is $$\lambda \sum_{a=1}^m b_a^2$$

**With the shrinkage penaly for LASSO, we get a more robust solution, but it is more unstable than Ridge Regression. We also have the potential for multiple solutions whereas with Ridge Regression, we always have one solution. LASSO also has the potential for feature selection whereas Ridge Regression does not. Ridge Regression has analytical solutions whereas LASSO does not, and LASSO can have sparse outputs whereas Ridge Regression does not.**

**LASSO tends to zero out parameters whereas Ridge Regression does not.**

**Additionally, LASSO does both parameter shrinkage and variable selection automatically. However, LASSO does not work well with collinearity, because it might randomly choose one the collinear variables, possibly eliminating relevant independent variables. Conversely, Ridge Regression does not eliminate coefficient even if the variables are irrelevant.**

In [13]:
# TODO: Create code for LASSO here
# TODO: Plot your regression line over the input points. 

from sklearn import linear_model

def LASSO(X, y, ridge=.001):
    clf = linear_model.Lasso(alpha=ridge)
    clf.fit(X, y)
    return clf.coef_
  

# TODO: check against training data
theta = LASSO(X_train,Y_train)
print(theta)

predicted_y = np.dot(X_train, theta)
error = ((predicted_y - Y_train) ** 2).mean()
print(f"Error: {error}")


# TODO: check against testing data

[ 2.99099792  2.01763613 -0.00368638]
Error: 74685.8140478333


**Explain** the effect elastic nets had on your values for theta compared to OLS. Also try different values for the ridge parameters and describe how they effect your results.



**Our theta values affected by elastic nets were larger compared to those affected by OLS. Larger values for the ridge parameter increase the error.**

**Explain** the differences between LASSO, Ridge Regression and Elastic Nets and how it changes the solution mathematically.

**Elastic Net combines feature elimination from LASSO and feature coefficient reduction from Ridge Regression, reducing the impact of different features while not eliminating all of them.**

In [14]:
# TODO: Create code for Elastic Nets here. You can use a library such as scipy
# TODO: Plot your regression line over the input points.
# from scipy
from sklearn.linear_model import ElasticNet
def EN(X,y):
    regr = ElasticNet(random_state=0)
    regr.tol = .001
    regr.fit(X, y)
    return regr.coef_

# TODO: check against training data
theta = EN(X_train,Y_train)
predicted_y = np.dot(X_train, theta)
error = ((predicted_y - Y_train) ** 2).mean()
print(f"Error: {error}")

# TODO: check against testing data

Error: 74679.33668781767


What is the purpose of a regularizer?

**A regularizer can prevent overfitting and complications to do with collinearity.**

Give two examples where a regularizer would give more robust models.

**A regularizer would give more robust models where... 1) your data has large outliers, and 2) your data sets are small.**

Explain with reference to the dataset why a regularizer achieved better performance than OLS.

**Our dataset had collinearity, reducing the precision of the estimate coefficients in OLS. The use of a regularizer minimized this issue.**

<hr class='light-separate' />

Implement feature transformation to fit a line to the curve generated from the .csv file.

In [15]:
X = np.genfromtxt('feature_transform.csv', delimiter=',')
y = X[:,2].reshape(500, 1)
X = X[:,:2]

In [16]:
# TODO: Write the lambda function phi which will transform X
# TODO: Plot the transformation and the resulting line after transforming

def phi(x, degree):
    # construct X matrix
    columns = []
    n = len(x)
    for i in range(degree + 1):
        if i == 0:
            columns.append(np.ones(n))
        else:
            columns.append(x**i)
    X = np.matrix(columns).T 
    return X

X_tran = phi(X[:,0], 3)
theta = OLS(X_tran, y)
y_hat = np.dot(X_tran, theta)
coef = np.array(theta).ravel()
phi_plot = np.linspace(0, 1, 500)

def poly_coefficents(x, coeffs):
    # Returns a polynomial for 'x' values for the 'coeffs' provided.
    k = len(coeffs)
    y = 0
    for i in range(k):
        y += coeffs[i]*x**i
    return y


import matplotlib.pyplot as plt
plt.plot(phi_plot, poly_coefficents(phi_plot, coef))
plt.scatter(X[:,0],y,color=(0.0,0.5,0.0))
plt.xlabel('X')
plt.ylabel('Y')
plt.show()

ModuleNotFoundError: No module named 'matplotlib'

<hr class='light-separate' />

Recall what you learned about polynomial regression and explain what is happening to the model as you increase the degrees. Run the cell below and use the slider to help you.

**As the slider increases, the degree of the polynomial used to represent the data increases with it. Because the line of best fit’s equation has changed, the model changes as well. This can be problematic because the polynomial begins to fit the training data really well but can start to lose meaning for any other data we’d like to test our model on. This is seen in the example because once the degree of the polynomial extends past 7 the end of the line begins to no longer fit the data well. It either abruptly goes up or down.**

In [17]:
# DO NOT ALTER

import pandas as pd
import ipywidgets as widgets
from ipywidgets import interact
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline

boston = datasets.load_boston()
data = pd.DataFrame(boston.data,columns=boston.feature_names)
data = pd.concat([data,pd.Series(boston.target,name='MEDV')],axis=1)

X = data[['LSTAT']].values
y = data['MEDV']

x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=42, shuffle=True)

temp = pd.DataFrame({'x':x_train.reshape(1, 354)[0], 'y':y_train})
temp = temp.sort_values('x')
x_train = temp['x'].values.reshape(354,1)
y_train = temp['y'].values

temp = pd.DataFrame({'x':x_test.reshape(1, 152)[0], 'y':y_test})
temp = temp.sort_values('x')
x_test = temp['x'].values.reshape(152,1)
y_test = temp['y'].values

def f(degree):
    model = make_pipeline(PolynomialFeatures(degree), LinearRegression())
    model.fit(x_train,y_train)
    y_plot = model.predict(x_test)
    
    plt.scatter(x_train, y_train, s=10, color='red', alpha=.3)
    plt.scatter(x_test, y_test, s=10)

    test_sr = (y_test - y_plot)**2
    test_ssr = test_sr.sum()
    test_asr = test_ssr/len(test_sr)
    
    y_plot_train = model.predict(x_train)
    train_sr = (y_train - y_plot_train)**2
    train_ssr = train_sr.sum()
    train_asr = train_ssr/len(train_sr)
    
    plt.plot(x_test, y_plot, label="degree %d" % degree + '; Test Error: %.2f' % test_asr + '; Train Error: %.2f' % train_asr, color='green')
    plt.legend(loc='upper right')
    plt.show()
    
interact(f, degree = widgets.IntSlider(min=1, max=20, step=1, value=1))

ModuleNotFoundError: No module named 'pandas'

Completed by Jennifer Mickel and Rebecca Riley